# zap logger configuration
zap:
  level: info
  format: console
  prefix: "[baileys]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

# system configuration
system:
  env: public # Change to "develop" to skip authentication for development mode
  addr: 8888
  #  路由全局前缀
  router-prefix: ""

use-redis: false

kubernetes:
  kubeconfig: /root/.kube/config # kubeconfig 文件路径
  in-cluster: false  # 是否在集群内运行，如果为 true 则 kubeconfig 无效

mysql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

# timer task db clear table
Timer:
  start: true
  spec: "@daily" # 定时任务详细配置参考 https://pkg.go.dev/github.com/robfig/cron/v3
  detail:
    - tableName: sys_operation_records
      compareField: created_at
      interval: 2160h
    - tableName: jwt_blacklists
      compareField: created_at
      interval: 168h
