definitions:
  request.GetPodListReq:
    properties:
      namespace:
        description: 命名空间
        type: string
    type: object
  response.ContainerInfo:
    properties:
      createAt:
        description: 创建时间
        type: string
      id:
        description: 容器ID
        type: string
      image:
        description: 容器镜像
        type: string
      name:
        description: 容器名
        type: string
      ready:
        description: 是否就绪
        type: boolean
      restartCount:
        description: 容器重启次数
        type: integer
      state:
        description: 容器运行状态
        type: string
      status:
        description: 容器详情
        type: string
    type: object
  response.GetContainerListResp:
    properties:
      containers:
        description: 容器列表
        items:
          $ref: '#/definitions/response.ContainerInfo'
        type: array
    type: object
  response.GetPodListResp:
    properties:
      pods:
        description: Pod列表
        items:
          $ref: '#/definitions/response.PodInfo'
        type: array
    type: object
  response.PodContainerInfo:
    properties:
      containerName:
        description: 容器名称
        type: string
      image:
        description: 容器镜像
        type: string
      podName:
        description: Pod名称
        type: string
      ready:
        description: 是否就绪
        type: boolean
    type: object
  response.PodInfo:
    properties:
      containerStatus:
        description: 容器状态
        type: string
      containers:
        description: 容器列表
        items:
          $ref: '#/definitions/response.PodContainerInfo'
        type: array
      createAt:
        description: 创建时间
        type: string
      podName:
        description: Pod名称
        type: string
      podStatus:
        description: Pod状态
        type: string
      restartCount:
        description: 重启次数
        type: integer
      runOften:
        description: 运行时长
        type: string
      workloadName:
        description: 工作负载名称
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /baileys/docker/getContainerList:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 创建基础api
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetContainerListResp'
                msg:
                  type: string
              type: object
      summary: 获取Docker容器列表
      tags:
      - ContainerApi
  /baileys/k8s/getPodList:
    post:
      consumes:
      - application/json
      parameters:
      - description: 命名空间
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.GetPodListReq'
      produces:
      - application/json
      responses:
        "200":
          description: 获取K8s Pod列表
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetPodListResp'
                msg:
                  type: string
              type: object
      summary: 获取K8s Pod列表
      tags:
      - PodApi
  /baileys/setting/getRuntime:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 创建基础api
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
                msg:
                  type: string
              type: object
      summary: 获取当前运行模式
      tags:
      - RuntimeApi
swagger: "2.0"
